---
 - hosts: ci
   become: yes
   become_user: root
   become_method: sudo
   tasks:
    - name: Create Jenkins container
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - jenkins_home:/var/jenkins_home
        restart_policy: unless-stopped
    