---
  - name: Add Certbot Repository
    apt_repository: repo='ppa:certbot/certbot' state=present
    register: repositoryinstalled

  - name: Install Certbot
    apt: pkg=python-certbot-nginx state=latest update_cache=true
    when: repositoryinstalled is success

  - name: Check If SSL Certificate Exists
    stat:
      path: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
    register: certificate
  
  - name: Stop Nginx
    service: name=nginx state=stopped
    when: not certificate.stat.exists

  - name: Install Certificate
    shell: certbot --noninteractive --agree-tos --email {{ email }} --nginx -d {{ domain }}
    when: not certificate.stat.exists
    notify:
      - Start Nginx

  - name: Add Certbot Renewal Cron Job
    cron:
      name: Certbot Renewal
      job: "certbot renew --quiet --no-self-upgrade"
      hour: "3"
      minute: "30"
      user: "root"
